# Custom Library with Authenticator in it
# We use the first one
#[target.aarch64-unknown-linux-gnueabihf]
#image = "opencvs-auth:musl2"
#
#[target.armv7-unknown-linux-musleabihf]
#image = "opencv:musl"

