# Custom Library with Authenticator in it
[target.armv7-unknown-linux-gnueabihf]
image = "local/armv7-unknown-linux-gnueabihf"

#[target.armv7-unknown-linux-musleabihf]
#image = "opencv:musl"

#[target.aarch64-unknown-linux-musl]
#image = "local/aarch64-unknown-linux-musl"
