# docker build --platform linux/arm64 -t local/aarch64-unknown-linux-musl . 
# docker buildx build --platform linux/arm64 -t local/aarch64-unknown-linux-musl .
FROM ghcr.io/cross-rs/aarch64-unknown-linux-musl:latest